// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhfxzsqfqwpsyiycxzjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpoZnh6c3FmcXdwc3lpeWN4empwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4NDE2OTIsImV4cCI6MjA1NTQxNzY5Mn0.8vxh8pBmO51N9w4Rq9SpcvBRES3-Dk2MaqxaU5k1w3E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);